# Generated by Django 4.0.5 on 2023-01-28 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ward", "0001_initial"),
        ("consultation_diagnosis", "0001_initial"),
        ("admission", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admission",
            name="attendance",
        ),
        migrations.RemoveField(
            model_name="admission",
            name="diagnosis",
        ),
        migrations.RemoveField(
            model_name="admission",
            name="patient",
        ),
        migrations.AddField(
            model_name="admission",
            name="consultation_diagnosis",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consultation_diagnosis_admission",
                to="consultation_diagnosis.consultationdiagnosis",
            ),
        ),
        migrations.AlterField(
            model_name="admission",
            name="ward",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="admission_ward",
                to="ward.ward",
            ),
        ),
    ]
