# Generated by Django 4.0.5 on 2023-02-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admission", "0006_alter_admission_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
