# Generated by Django 4.0.5 on 2023-03-07 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_patient_hospital_record_no'),
        ('diagnosis', '0001_initial'),
        ('admission', '0007_alter_admission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='consultation_diagnosis',
        ),
        migrations.AddField(
            model_name='admission',
            name='diagnosis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_admission', to='diagnosis.diagnosis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patient_admission', to='person.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
