# Generated by Django 4.0.5 on 2023-03-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_diagnosis', '0003_consultationdiagnosis_ipd'),
        ('admission', '0008_remove_admission_consultation_diagnosis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='patient',
        ),
        migrations.AddField(
            model_name='admission',
            name='consultation_diagnosis',
            field=models.ForeignKey(default=47, on_delete=django.db.models.deletion.CASCADE, related_name='patient_admission', to='consultation_diagnosis.consultationdiagnosis'),
            preserve_default=False,
        ),
    ]
