# Generated by Django 4.0.5 on 2023-01-24 09:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import validator.views


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("status", "0001_initial"),
        ("town", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("facility_category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Facility Name"),
                ),
                ("website", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "contact_name",
                    models.CharField(max_length=100, verbose_name="Contact Name"),
                ),
                (
                    "registration_no",
                    models.CharField(
                        max_length=100, verbose_name="Health service registration"
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="logos",
                        validators=[
                            validator.views.validate_file_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "png", "bmp", "jfif"]
                            ),
                        ],
                        verbose_name="Logo",
                    ),
                ),
                (
                    "primary_phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+233000000000'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Primary Phone",
                    ),
                ),
                (
                    "secondary_phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+233000000000'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Secondary Phone",
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                ("street", models.CharField(max_length=100)),
                (
                    "postcode",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Postcode or Post Box",
                    ),
                ),
                (
                    "digital_address",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name=" Digital Address",
                    ),
                ),
                ("default_facility", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facility_cat",
                        to="facility_category.facilitycategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        max_length=100,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facility_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facility_status",
                        to="status.status",
                    ),
                ),
                (
                    "town",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facility_town",
                        to="town.town",
                    ),
                ),
            ],
        ),
    ]
