# Generated by Django 4.0.5 on 2023-03-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='health_facility_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Health Facility Code'),
        ),
    ]
