# Generated by Django 4.0.5 on 2023-01-28 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("radiology_procedure", "0001_initial"),
        ("currency_type", "0001_initial"),
        ("sponsor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RadiologyProcedurePriceSponsor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("decription", models.TextField()),
                ("percentage_allowed", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="currency_type_radiology_procedure_price_sponsor",
                        to="currency_type.currencytype",
                    ),
                ),
                (
                    "radiology_procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="radiology_procedure_price_sponsor_radiology_procedure",
                        to="radiology_procedure.radiologyprocedure",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sponsor_radiology_procedure_price_sponsor",
                        to="sponsor.sponsor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
