# Generated by Django 4.0.5 on 2023-03-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology_procedure_price_sponsor', '0002_alter_radiologyprocedurepricesponsor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologyprocedurepricesponsor',
            name='percentage_allowed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='radiologyprocedurepricesponsor',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
