# Generated by Django 4.0.5 on 2023-03-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology_procedure_price_sponsor', '0003_alter_radiologyprocedurepricesponsor_percentage_allowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologyprocedurepricesponsor',
            name='decription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
