# Generated by Django 4.0.5 on 2023-02-22 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intervention_implementation', '0001_initial'),
        ('nurses_note', '0004_alter_nursesnote_id'),
        ('intervention_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionimplementation',
            name='intervention_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inteventation_type_intervention_implementation', to='intervention_type.interventiontype'),
        ),
        migrations.AddField(
            model_name='interventionimplementation',
            name='nurses_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurses_note_intervention_implementation', to='nurses_note.nursesnote'),
        ),
    ]
