# Generated by Django 4.0.5 on 2023-01-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0003_alter_room_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
