# Generated by Django 4.0.5 on 2023-02-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0004_alter_room_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="number",
            field=models.CharField(max_length=100),
        ),
    ]
