# Generated by Django 4.0.5 on 2023-03-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology_category', '0002_alter_radiologycategory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologycategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
