# Generated by Django 4.0.5 on 2023-01-24 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("status", "0001_initial"),
        ("relative_type", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Relative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_relative",
                        to="person.patient",
                    ),
                ),
                (
                    "relative_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_relative",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "relative_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_relative_type",
                        to="relative_type.relativetype",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relative_status",
                        to="status.status",
                    ),
                ),
            ],
        ),
    ]
