# Generated by Django 4.0.5 on 2023-01-24 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("status", "0001_initial"),
        ("daily_attendance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vital_sign", models.BooleanField(default=False)),
                ("consultation", models.BooleanField(default=False)),
                ("diagnosis", models.BooleanField(default=False)),
                ("lab", models.BooleanField(default=False)),
                ("procedure", models.BooleanField(default=False)),
                ("prescription", models.BooleanField(default=False)),
                ("medication", models.BooleanField(default=False)),
                ("registration_fee", models.BooleanField(default=False)),
                ("consultation_fee", models.BooleanField(default=False)),
                ("procedure_fee", models.BooleanField(default=False)),
                ("lab_bill", models.BooleanField(default=False)),
                ("medication_bill", models.BooleanField(default=False)),
                ("end_process", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "attendance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="daily_attendance.dailyattendancemodel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_bar_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_status",
                        to="status.status",
                    ),
                ),
            ],
        ),
    ]
