# Generated by Django 4.0.5 on 2023-01-28 00:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("person", "0001_initial"),
        ("procedure", "0001_initial"),
        ("status", "0001_initial"),
        ("doctors_note", "0001_initial"),
        ("admission", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcedureCare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedure_care_admission",
                        to="admission.admission",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doctor_procedure_care",
                        to="person.staff",
                    ),
                ),
                (
                    "doctor_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doctor_note_procedure_care",
                        to="doctors_note.doctorsnote",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedure_care_patient",
                        to="person.patient",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedure_procedure_care",
                        to="procedure.procedure",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="status_procedure_care",
                        to="status.status",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
