# Generated by Django 4.0.5 on 2023-02-28 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_alter_loggedinuserdevices_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procedure_care', '0005_procedurecare_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedurecare',
            name='doctor',
        ),
        migrations.AddField(
            model_name='procedurecare',
            name='nurse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='nurse_procedure_care', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procedurecare',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_care_patient', to='person.patient'),
        ),
    ]
