# Generated by Django 4.0.5 on 2023-02-22 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('occupation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nurses_note', '0004_alter_nursesnote_id'),
        ('marital_status', '0001_initial'),
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('family_situation', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('sexual_history', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupation_social_history', to='habit.habit')),
                ('marital_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marital_status_social_history', to='marital_status.maritalstatus')),
                ('nurses_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurses_note_social_history', to='nurses_note.nursesnote')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupation_social_history', to='occupation.occupation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
