# Generated by Django 4.0.5 on 2023-03-10 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_history', '0002_socialhistory_admission_socialhistory_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialhistory',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='socialhistory',
            name='patient',
        ),
    ]
