# Generated by Django 4.0.5 on 2023-03-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_history', '0004_socialhistory_admission_socialhistory_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialhistory',
            name='admission',
        ),
    ]
