# Generated by Django 4.0.5 on 2023-03-11 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nurses_note', '0005_alter_nursesnote_nurse'),
        ('allergies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergies',
            name='nurses_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurses_note_allergies', to='nurses_note.nursesnote'),
        ),
    ]
