# Generated by Django 4.0.5 on 2023-01-24 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("unit_of_measurement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicationUnitOfMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selling_unit", models.BooleanField()),
                (
                    "brand",
                    models.TextField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                ("bar_code", models.TextField(blank=True, max_length=200, null=True)),
                ("drug_code", models.TextField(blank=True, max_length=100, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("NHIS_list", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("approved", "Approved"),
                            ("active", "Active"),
                            ("deactivate", "Deactivate"),
                            ("suspended", "Suspended"),
                            ("delete", "Delete"),
                            ("closed", "Closed"),
                            ("registered", "Registered"),
                            ("vital done", "Vital Done"),
                            ("diagnosed", "Diagnosed"),
                            ("billed", "Billed"),
                            ("pending lab", "Pending Lab"),
                            ("pending pharmacy", "Pending Pharmacy"),
                        ],
                        default="active",
                        max_length=100,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_unit_of_measurement_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit_of_measurement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_of_measurement_with_medication",
                        to="unit_of_measurement.unitofmeasurement",
                    ),
                ),
            ],
        ),
    ]
