# Generated by Django 4.0.5 on 2023-02-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstetric_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obstetrichistory',
            name='size_of_wound',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
