# Generated by Django 4.0.5 on 2023-03-10 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obstetric_history', '0003_obstetrichistory_admission_obstetrichistory_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obstetrichistory',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='obstetrichistory',
            name='patient',
        ),
    ]
