# Generated by Django 4.0.5 on 2023-03-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obstetric_history', '0005_obstetrichistory_admission_obstetrichistory_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obstetrichistory',
            name='admission',
        ),
    ]
