# Generated by Django 4.0.5 on 2023-01-24 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quantity_unit_type", "0001_initial"),
        ("supplier", "0001_initial"),
        ("status", "0001_initial"),
        ("warehouse_product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=1, default=0, max_digits=10),
                ),
                (
                    "cost_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("note", models.TextField(blank=True, max_length=200, null=True)),
                ("batch_no", models.TextField(blank=True, max_length=200, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_stock_quantity_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quantity_unit_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quantity_unit_type_id",
                        to="quantity_unit_type.quantityunittype",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="status.status"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wharehouse_supplier_in_stock",
                        to="supplier.supplier",
                    ),
                ),
                (
                    "warehouse_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_product_id_in_stock",
                        to="warehouse_product.warehouseproduct",
                    ),
                ),
            ],
        ),
    ]
