# Generated by Django 4.0.5 on 2023-02-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousestock',
            name='reorder_level',
            field=models.IntegerField(default=0),
        ),
    ]
