# Generated by Django 4.0.5 on 2023-02-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_stock', '0002_warehousestock_reorder_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousestock',
            name='ordered_quantity',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
