# Generated by Django 4.0.5 on 2023-03-07 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_patient_hospital_record_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admission', '0008_remove_admission_consultation_diagnosis_and_more'),
        ('treatment_plan', '0008_alter_treatmentplan_objectives'),
        ('doctors_note', '0005_alter_doctorsnote_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsnote',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors_note_admission', to='admission.admission'),
        ),
        migrations.AlterField(
            model_name='doctorsnote',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors_note_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorsnote',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorsnote',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors_note_patient', to='person.patient'),
        ),
        migrations.AlterField(
            model_name='doctorsnote',
            name='treatment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors_note_treatment_plan', to='treatment_plan.treatmentplan'),
        ),
    ]
