# Generated by Django 4.0.5 on 2023-02-24 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nurses_note', '0005_alter_nursesnote_nurse'),
        ('family_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyhistory',
            name='brief_history',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='nurses_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurses_note_family_history', to='nurses_note.nursesnote'),
        ),
    ]
