# Generated by Django 4.0.5 on 2023-03-10 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_history', '0003_familyhistory_admission_familyhistory_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyhistory',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='familyhistory',
            name='patient',
        ),
    ]
