# Generated by Django 4.0.5 on 2023-03-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_history', '0005_familyhistory_admission_familyhistory_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyhistory',
            name='admission',
        ),
    ]
