# Generated by Django 4.0.5 on 2023-02-18 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_plan', '0004_alter_treatmentplan_doctor'),
        ('medication_administration', '0004_alter_medicationadministration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationadministration',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicationadministration',
            name='treatment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plan_medication_administration', to='treatment_plan.treatmentplan'),
        ),
    ]
