# Generated by Django 4.0.5 on 2023-02-28 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medication_administration', '0005_medicationadministration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationadministration',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_administration_nurse', to=settings.AUTH_USER_MODEL),
        ),
    ]
