# Generated by Django 4.0.5 on 2023-03-07 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_patient_hospital_record_no'),
        ('medication_administration', '0006_alter_medicationadministration_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationadministration',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_administration_patient', to='person.patient'),
        ),
    ]
