# Generated by Django 4.0.5 on 2023-03-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology_procedure', '0003_radiologyprocedure_gdrg_radiologyprocedure_icd_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologyprocedure',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
