# Generated by Django 4.0.5 on 2023-01-31 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patient_type", "0001_initial"),
        ("consultation_diagnosis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultationdiagnosis",
            name="patient_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patient_type_consultation_diagnosis",
                to="patient_type.patienttype",
            ),
        ),
    ]
