# Generated by Django 4.0.5 on 2023-02-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultation_diagnosis", "0002_consultationdiagnosis_patient_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultationdiagnosis",
            name="ipd",
            field=models.BooleanField(default=False),
        ),
    ]
