# Generated by Django 4.0.5 on 2023-01-28 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("radiology_procedure_result", "0001_initial"),
        ("warehouse_product", "0001_initial"),
        ("radiology_material_used", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="radiologymaterialused",
            name="radiology_procedure_result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="radiology_procedure_result_radiology_material_used",
                to="radiology_procedure_result.radiologyprocedureresult",
            ),
        ),
        migrations.AddField(
            model_name="radiologymaterialused",
            name="warehouse_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="radiology_procedure_result_radiology_material_used",
                to="warehouse_product.warehouseproduct",
            ),
        ),
    ]
