# Generated by Django 4.0.5 on 2023-02-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bed_allocation", "0004_bedallocation_allocated_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bedallocation",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="bedallocation",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
