# Generated by Django 4.0.5 on 2023-01-24 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("consultation_diagnosis", "0001_initial"),
        ("sponsor", "0001_initial"),
        ("status", "0001_initial"),
        ("warehouse_product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=1, default=0, max_digits=10),
                ),
                ("duration", models.IntegerField(default=0)),
                (
                    "duration_unit",
                    models.CharField(
                        choices=[("day", "DAY"), ("week", "WEEK"), ("month", "MONTH")],
                        default="day",
                        max_length=100,
                    ),
                ),
                (
                    "prescription_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "consultation_diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescribed_to",
                        to="consultation_diagnosis.consultationdiagnosis",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescribed_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsor_prescription",
                        to="sponsor.sponsor",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescribed_status",
                        to="status.status",
                    ),
                ),
                (
                    "warehouse_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescribed_medicine",
                        to="warehouse_product.warehouseproduct",
                    ),
                ),
            ],
        ),
    ]
