# Generated by Django 4.0.5 on 2023-01-24 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sponsor", "0001_initial"),
        ("status", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SponsorPatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "memberId",
                    models.CharField(
                        help_text="This is the identity number used to identify the patient by the insurance other companies ",
                        max_length=100,
                    ),
                ),
                (
                    "copay_percentage",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("bill_limit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("valid_from", models.DateField(default=django.utils.timezone.now)),
                ("valid_to", models.DateField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="System User",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_sponsor",
                        to="person.patient",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsor_in_patient",
                        to="sponsor.sponsor",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_sponsor_patient",
                        to="status.status",
                    ),
                ),
            ],
        ),
    ]
