# Generated by Django 4.0.5 on 2023-03-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorpatient',
            name='nhis_serial_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NHIS Serial Number'),
        ),
    ]
