# Generated by Django 4.0.5 on 2023-01-28 00:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ward_type", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=100)),
                (
                    "ward_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ward_wardtype",
                        to="ward_type.wardtype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
