# Generated by Django 4.0.5 on 2023-01-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ward", "0003_alter_ward_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ward",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ward",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
