# Generated by Django 4.0.5 on 2023-02-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0003_loggedinuserdevices"),
    ]

    operations = [
        migrations.AddField(
            model_name="loggedinuserdevices",
            name="browser",
            field=models.CharField(default="Chrome", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loggedinuserdevices",
            name="os",
            field=models.CharField(default="Mac", max_length=255),
            preserve_default=False,
        ),
    ]
