# Generated by Django 4.0.5 on 2023-02-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0004_loggedinuserdevices_browser_loggedinuserdevices_os"),
    ]

    operations = [
        migrations.AddField(
            model_name="loggedinuserdevices",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
