# Generated by Django 4.0.5 on 2023-02-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_loggedinuserdevices_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loggedinuserdevices',
            options={'ordering': ['-id']},
        ),
    ]
