# Generated by Django 4.0.5 on 2023-03-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_alter_loggedinuserdevices_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hospital_record_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hospital Record Number'),
        ),
    ]
