# Generated by Django 4.0.5 on 2023-01-24 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("order_batch", "0001_initial"),
        ("department", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quantity_unit_type", "0001_initial"),
        ("status", "0001_initial"),
        ("warehouse_product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentStockOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_quantity",
                    models.DecimalField(decimal_places=1, default=0, max_digits=10),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_order_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department",
                        to="department.department",
                    ),
                ),
                (
                    "order_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_batch",
                        to="order_batch.orderbatch",
                    ),
                ),
                (
                    "order_quantity_unit_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_quantity_unit_type",
                        to="quantity_unit_type.quantityunittype",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="status.status"
                    ),
                ),
                (
                    "warehouse_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wharehouse_supplier_in_stock",
                        to="warehouse_product.warehouseproduct",
                    ),
                ),
            ],
        ),
    ]
