# Generated by Django 4.0.5 on 2023-03-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('need_type', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needtype',
            name='nurses_note',
        ),
    ]
