# Generated by Django 4.0.5 on 2023-03-05 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_diagnosis', '0003_consultationdiagnosis_ipd'),
        ('inter_hospital_patient_transfer', '0004_alter_interhospitalpatienttransfer_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interhospitalpatienttransfer',
            name='patient',
        ),
        migrations.AddField(
            model_name='interhospitalpatienttransfer',
            name='consultation_diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interhosppatienttrans_consultation_diagnosis', to='consultation_diagnosis.consultationdiagnosis'),
        ),
    ]
