# Generated by Django 4.0.5 on 2023-03-07 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_patient_hospital_record_no'),
        ('admission', '0008_remove_admission_consultation_diagnosis_and_more'),
        ('inter_hospital_patient_transfer', '0005_remove_interhospitalpatienttransfer_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interhospitalpatienttransfer',
            name='consultation_diagnosis',
        ),
        migrations.AddField(
            model_name='interhospitalpatienttransfer',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patient_inter_hospital_patient_transfer', to='person.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interhospitalpatienttransfer',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interhosppatienttrans_admission', to='admission.admission'),
        ),
        migrations.AlterField(
            model_name='interhospitalpatienttransfer',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interhospitalpatienttransfer',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
