# Generated by Django 4.0.5 on 2023-02-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychosocial_history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psychosocialhistory',
            old_name='psychosocial_health',
            new_name='behavorial_health',
        ),
        migrations.AddField(
            model_name='psychosocialhistory',
            name='psychological_health',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
