# Generated by Django 4.0.5 on 2023-03-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychosocial_history', '0003_psychosocialhistory_admission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychosocialhistory',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='psychosocialhistory',
            name='patient',
        ),
    ]
