# Generated by Django 4.0.5 on 2023-03-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychosocial_history', '0005_psychosocialhistory_admission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychosocialhistory',
            name='admission',
        ),
    ]
