# Generated by Django 4.0.5 on 2023-01-28 00:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("person", "0001_initial"),
        ("admission", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatmentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("objectives", models.TextField()),
                ("estimated_admission_duration", models.CharField(max_length=50)),
                ("treatment_relationale", models.TextField()),
                ("has_accessed_prev_nurses_note", models.BooleanField(default=False)),
                ("patient_condition", models.CharField(max_length=255)),
                (
                    "admission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatmentplan_admission",
                        to="admission.admission",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatement_plan_doctor",
                        to="person.staff",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatmentplan_patient",
                        to="person.patient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
