# Generated by Django 4.0.5 on 2023-02-05 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0001_initial"),
        ("treatment_plan", "0003_alter_treatmentplan_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatmentplan",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="treatement_plan_doctor",
                to="person.staff",
            ),
        ),
    ]
