# Generated by Django 4.0.5 on 2023-02-24 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treatment_plan', '0006_alter_treatmentplan_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentplan',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plan_doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
