# Generated by Django 4.0.5 on 2023-02-22 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nurses_note', '0004_alter_nursesnote_id'),
        ('need_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientNeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('need_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='need_type_patient_needs', to='need_type.needtype')),
                ('nurses_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurses_note_patient_needs', to='nurses_note.nursesnote')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
