# Generated by Django 4.0.5 on 2023-03-10 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_habit_admission_habit_patient_habit_treatment_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='patient',
        ),
    ]
