# Generated by Django 4.0.5 on 2023-03-10 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_remove_admission_consultation_diagnosis_and_more'),
        ('person', '0007_patient_hospital_record_no'),
        ('habit', '0004_remove_habit_admission_remove_habit_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='admission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admission_habit', to='admission.admission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patient_habit', to='person.patient'),
            preserve_default=False,
        ),
    ]
