# Generated by Django 4.0.5 on 2023-03-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0005_habit_admission_habit_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='admission',
        ),
    ]
