# Generated by Django 4.0.5 on 2023-02-24 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
        ('immunizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunizations',
            name='disease',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disease_immunizations', to='diagnosis.diagnosis'),
            preserve_default=False,
        ),
    ]
