# Generated by Django 4.0.5 on 2023-03-10 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immunizations', '0003_immunizations_admission_immunizations_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immunizations',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='immunizations',
            name='patient',
        ),
    ]
