# Generated by Django 4.0.5 on 2023-03-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immunizations', '0005_immunizations_admission_immunizations_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immunizations',
            name='admission',
        ),
    ]
