# Generated by Django 4.0.5 on 2023-03-21 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
        ('sample_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampletype',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sample_type_status', to='status.status'),
        ),
    ]
