# Generated by Django 4.0.5 on 2023-02-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bed", "0003_alter_bed_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bed",
            name="number",
            field=models.CharField(max_length=255),
        ),
    ]
