# Generated by Django 4.0.5 on 2023-02-22 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nurses_note', '0004_alter_nursesnote_id'),
        ('diagnosis', '0001_initial'),
        ('treatment_plan', '0005_alter_treatmentplan_patient_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_patient_diagnosis', to='diagnosis.diagnosis')),
                ('nurses_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_diagnosis_nurses_note', to='nurses_note.nursesnote')),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plan_patient_diagnosis', to='treatment_plan.treatmentplan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
