# Generated by Django 4.0.5 on 2023-02-24 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nurses_note', '0004_alter_nursesnote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursesnote',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nurses_note_nurse', to=settings.AUTH_USER_MODEL),
        ),
    ]
