# Generated by Django 4.0.5 on 2023-01-24 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("consulting_room", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("daily_attendance", "0001_initial"),
        ("select_unit", "0001_initial"),
        ("status", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VitalSign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "respiration_freq",
                    models.CharField(
                        blank=True,
                        help_text="This specifies the breathing rate",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "oxygen_saturation",
                    models.CharField(
                        blank=True,
                        help_text="This indicates the level of oxygen",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "heart_rate",
                    models.CharField(
                        blank=True,
                        help_text="This indicates the heart or pulse rate",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "systolic_pressure",
                    models.CharField(
                        blank=True, help_text=" ", max_length=100, null=True
                    ),
                ),
                (
                    "diastolic_pressure",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "consciousness_level",
                    models.CharField(
                        blank=True,
                        help_text="This indicates consciousness level of patient ",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "temperature_location",
                    models.CharField(
                        blank=True,
                        help_text="This specifies where the temperature was taken",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "pulse_rhythm",
                    models.CharField(
                        blank=True,
                        help_text="This indicates whether the pulse rate is regular or irregular",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "history",
                    models.TextField(
                        blank=True,
                        help_text="This specifies the complains given by the patient ",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=250, null=True)),
                ("has_consultation", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vital_sign_patient",
                        to="daily_attendance.dailyattendancemodel",
                    ),
                ),
                (
                    "consulting_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cons_room",
                        to="consulting_room.consultingroom",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vital_sign_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diastolic_pressure_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diastolic_unit",
                        to="select_unit.selectunit",
                    ),
                ),
                (
                    "heart_rate_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heart_rate_unit",
                        to="select_unit.selectunit",
                    ),
                ),
                (
                    "height_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hight_unit",
                        to="select_unit.selectunit",
                    ),
                ),
                (
                    "oxygen_saturation_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oxygen_sat_unit",
                        to="select_unit.selectunit",
                    ),
                ),
                (
                    "respiration_freq_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resp_unit",
                        to="select_unit.selectunit",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="select_item_status",
                        to="status.status",
                    ),
                ),
                (
                    "systolic_pressure_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="systolic_unit",
                        to="select_unit.selectunit",
                    ),
                ),
                (
                    "temperature_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temp_unit",
                        to="select_unit.selectunit",
                    ),
                ),
                (
                    "weight_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_unit",
                        to="select_unit.selectunit",
                    ),
                ),
            ],
        ),
    ]
