# Generated by Django 4.0.5 on 2023-01-28 00:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("person", "0001_initial"),
        ("admission", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntraHospitalPatientTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("reason", models.TextField()),
                ("remarks", models.TextField()),
                (
                    "admission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="intrahosppatienttrans_admission",
                        to="admission.admission",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="intrahosppatienttrans_patient",
                        to="person.patient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
