# Generated by Django 4.0.5 on 2023-02-10 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0001_initial"),
        (
            "intra_hospital_patient_transfer",
            "0003_alter_intrahospitalpatienttransfer_id",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="intrahospitalpatienttransfer",
            name="destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intra_hospital_patient_transfer_destination",
                to="facility.facility",
            ),
        ),
        migrations.AlterField(
            model_name="intrahospitalpatienttransfer",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intra_hospital_patient_transfer_source",
                to="facility.facility",
            ),
        ),
    ]
