# Generated by Django 4.0.5 on 2023-02-11 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ward", "0004_alter_ward_description_alter_ward_location"),
        (
            "intra_hospital_patient_transfer",
            "0004_alter_intrahospitalpatienttransfer_destination_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="intrahospitalpatienttransfer",
            name="destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intra_hospital_patient_transfer_destination",
                to="ward.ward",
            ),
        ),
        migrations.AlterField(
            model_name="intrahospitalpatienttransfer",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intra_hospital_patient_transfer_source",
                to="ward.ward",
            ),
        ),
    ]
