# Generated by Django 4.0.5 on 2023-03-05 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_diagnosis', '0003_consultationdiagnosis_ipd'),
        ('intra_hospital_patient_transfer', '0005_alter_intrahospitalpatienttransfer_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intrahospitalpatienttransfer',
            name='patient',
        ),
        migrations.AddField(
            model_name='intrahospitalpatienttransfer',
            name='consultation_diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intrahosppatienttrans_patient', to='consultation_diagnosis.consultationdiagnosis'),
        ),
    ]
